USE bitrix;

CREATE TABLE IF NOT EXISTS language
(
    ID char(2) NOT NULL,
    NAME varchar(250) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS movie
(
    ID INT NOT NULL AUTO_INCREMENT,
    RELEASE_YEAR YEAR,
    LENGTH INT,
    MIN_AGE INT,
    RATING float,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS movie_title
(
    LANGUAGE_ID CHAR(2) NOT NULL,
    MOVIE_ID INT NOT NULL,
    TITLE VARCHAR(250) NOT NULL,
    PRIMARY KEY (MOVIE_ID, LANGUAGE_ID),
    FOREIGN KEY (LANGUAGE_ID) REFERENCES language(ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    FOREIGN KEY (MOVIE_ID) REFERENCES movie(ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS people
(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME varchar(250) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS professions
(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME varchar(256) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS heroes
(
    MOVIE_ID INT NOT NULL,
    PEOPLE_ID INT NOT NULL,
    HEROES_NAME varchar(256) NOT NULL,
    UNIQUE KEY (MOVIE_ID, PEOPLE_ID, HEROES_NAME),
    FOREIGN KEY (MOVIE_ID) REFERENCES movie(ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    FOREIGN KEY (PEOPLE_ID) REFERENCES people(ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS movie_professions
(
    MOVIE_ID int NOT NULL,
    PEOPLE_ID int NOT NULL,
    PROFESSIONS_ID int NOT NULL,
    PRIMARY KEY (MOVIE_ID, PEOPLE_ID, PROFESSIONS_ID),
    FOREIGN KEY (MOVIE_ID) REFERENCES movie(ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    FOREIGN KEY (PEOPLE_ID) REFERENCES people(ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    FOREIGN KEY (PROFESSIONS_ID) REFERENCES professions(ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);